[package]
name = "jsoncrawler"
version = "0.1.0"
edition = "2021"
description = "fast json web crawler with storage abilities"
publish = false

[dependencies]
env_logger = "0.9.0"
jsoncrawler_lib = { path = "../jsoncrawler_lib" }
