[package]
name = "benches"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
jsoncrawler_lib = { path = "../jsoncrawler_lib" }
criterion = { version = "0.3.5", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "crawl"
path = "crawl.rs"
harness = false